const { Router } = require('express');
const dashboardRoutes = require('../modules/dashboard/dashboard.routes');
const authRoutes = require('../modules/auth/auth.routes');
const userRoutes = require('../modules/users/user.routes');
const roleRoutes = require('../modules/roles/role.routes');
const permissionRoutes = require('../modules/permissions/permission.routes');
const companyRoutes = require('../modules/companies/company.routes');
const departmentRoutes = require('../modules/departments/department.routes');
const designationRoutes = require('../modules/designations/designation.routes');
const employeeRoutes = require('../modules/employees/employee.routes');
const managerRoutes = require('../modules/managers/manager.routes');
const attendanceRoutes = require('../modules/attendance/attendance.routes');
const geofenceRoutes = require('../modules/geofences/geofence.routes');
const shiftRoutes = require('../modules/shifts/shift.routes');
const policyRoutes = require('../modules/attendance-policies/policy.routes');
const leaveRoutes = require('../modules/leave/leaveRequest.routes');
const compOffRoutes = require('../modules/comp-off/compOff.routes');
const regularizationRoutes = require('../modules/regularization/regularization.routes');
const wfhRoutes = require('../modules/wfh/wfh.routes');
const leavePolicyRoutes = require('../modules/leave-policies/policy.routes');
const workflowRoutes = require('../modules/workflow/workflow.routes');
const policyEngineRoutes = require('../modules/policy-engine/policyEngine.routes');
const notificationRoutes = require('../modules/notifications/notification.routes');
const holidayRoutes = require('../modules/holidays/holiday.routes');
const auditRoutes = require('../modules/audit/auditLog.routes');

const router = Router();

router.use('/dashboard', dashboardRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/companies', companyRoutes);
router.use('/departments', departmentRoutes);
router.use('/designations', designationRoutes);
router.use('/employees', employeeRoutes);
router.use('/managers', managerRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/geofences', geofenceRoutes);
router.use('/shifts', shiftRoutes);
router.use('/attendance-policies', policyRoutes);
router.use('/leave', leaveRoutes);
router.use('/comp-off', compOffRoutes);
router.use('/regularization', regularizationRoutes);
router.use('/wfh', wfhRoutes);
router.use('/leave-policies', leavePolicyRoutes);
router.use('/workflow', workflowRoutes);
router.use('/policy-engine', policyEngineRoutes);
router.use('/notifications', notificationRoutes);
router.use('/holidays', holidayRoutes);
router.use('/audit-logs', auditRoutes);

module.exports = router;
